title: Lakokocsis
email: laszlo1965@gmail.com
name: Viostream
repository: 'marklaszlo9/jekyll'
permalink: /blog/:year/:month/:day/:title
markdown: kramdown
plugins:
  - jekyll-assets
description: > # this means to ignore newlines until "baseurl:"
  Engage &amp; educate your audience with video. Viostream is the complete online video platform solution - helping businesses since 2002. Get a FREE trial today.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://viostream.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: viostream
github_username:  viostream
permalink: /blog/:year/:month/:day/:title


sass:
  sass_dir: _sass